// 'use client';

import { title } from "process";

// import { Inter } from 'next/font/google';
// import './globals.css';
// import { AuthProvider } from '@/context/authContext';

// const inter = Inter({ subsets: ['latin'] });

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <head>
//         <title>Steponext Product</title>
//         <meta name="description" content="Generated by Steponext" />
//       </head>
//       <body className={inter.className}>
//         <AuthProvider>
//           {children}
//         </AuthProvider>
//       </body>
//     </html>
//   );
// }


import { Inter } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '@/context/authContext';

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Steponext Product</title>
        <meta name="description" content="Generated by Steponext" />
      </head>
      <body className={inter.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}  