// import { Inter } from 'next/font/google';
// import './globals.css';
// import { Providers } from './providers';
// import { getServerSession } from 'next-auth';
// import { authOptions } from '@/lib/nextauth';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Steponext Product',
//   description: 'Generated by Steponext',
// };

// export default async function RootLayout({ children }) {
//   // ✅ This will work with JavaScript
//   const session = await getServerSession(authOptions);
  
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <head>
//         <link rel="icon" href="/favicon.ico" />
//         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
//         <meta name="theme-color" content="#ffffff" />
//       </head>
//       <body className={inter.className}>
//         <Providers session={session}>
//           {children}
//         </Providers>
//       </body>
//     </html>
//   );
// }

import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '../lib/nextauth';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Steponext Product',
  description: 'Professional E-commerce Platform',
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="theme-color" content="#ffffff" />
        <meta name="description" content={metadata.description} />
        
        {/* Open Graph Meta Tags */}
        <meta property="og:title" content={metadata.title} />
        <meta property="og:description" content={metadata.description} />
        <meta property="og:type" content="website" />
        
        {/* Twitter Card Meta Tags */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content={metadata.title} />
        <meta name="twitter:description" content={metadata.description} />
      </head>
      <body className={inter.className}>
        <Providers session={session}>
          {children}
        </Providers>
        
        {/* Global loading indicator - Clean version */}
        <div id="global-loader">
          <div className="loader-spinner"></div>
        </div>
      </body>
    </html>
  );
}